# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: List build artifacts
        run: ls -alh build/libs
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: Artifacts
          path: ./artifacts

      - name: Resolve artifact file names
        id: artifact_paths
        shell: bash
        run: |
          set -euo pipefail
          JAR=$(ls ./artifacts/*.jar | grep -v sources | head -n 1)
          echo "jar_path=$JAR" >> "$GITHUB_OUTPUT"
          echo "jar_name=$(basename "$JAR")" >> "$GITHUB_OUTPUT"
          SRC=$(ls ./artifacts/*-sources.jar | head -n 1 || true)
          if [ -n "${SRC:-}" ]; then
            echo "sources_path=$SRC" >> "$GITHUB_OUTPUT"
            echo "sources_name=$(basename "$SRC")" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (JAR)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.artifact_paths.outputs.jar_path }}
          asset_name: ${{ steps.artifact_paths.outputs.jar_name }}
          asset_content_type: application/java-archive

      - name: Upload Release Asset (Sources JAR)
        if: ${{ steps.artifact_paths.outputs.sources_path != '' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.artifact_paths.outputs.sources_path }}
          asset_name: ${{ steps.artifact_paths.outputs.sources_name }}
          asset_content_type: application/java-archive
      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: hvbQANV1
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-files: ${{ steps.artifact_paths.outputs.jar_path }}
